const directionName=vector=>vector.x===0&&vector.y===-1?'up':vector.x===0&&vector.y===1?'down':vector.x===-1?'left':'right';

export const getSegmentVisualType=(previous,current,next)=>{
  if(previous.x===next.x)return 'body-vertical';
  if(previous.y===next.y)return 'body-horizontal';
  const links=[{x:previous.x-current.x,y:previous.y-current.y},{x:next.x-current.x,y:next.y-current.y}].map(directionName);
  if(links.includes('up')&&links.includes('left'))return 'corner-ul';
  if(links.includes('up')&&links.includes('right'))return 'corner-ur';
  if(links.includes('down')&&links.includes('left'))return 'corner-dl';
  return 'corner-dr';
};

export class RenderSystem {
  constructor(canvas,config,assetLoader,gridSystem,layoutSystem){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.config=config;this.assetLoader=assetLoader;this.grid=gridSystem;this.layout=layoutSystem;this.skinAssets=new Map();this.loadingSkins=new Set();this.lastGame=null;}
  render(game){
    this.lastGame=game;this.ensureSkin(game.skinSystem.current);
    const {ctx,canvas}=this,map=game.mapSystem.current,camera=game.cameraSystem,cell=this.grid.getCellSize(),viewport=this.layout.viewport,start=Math.floor(camera.y)-1,end=Math.ceil(camera.y)+viewport.rows+1;
    if(!cell)return;
    ctx.fillStyle='#0b0c0c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#171919';ctx.lineWidth=1;
    for(let x=0;x<=map.grid.cols;x+=1){const px=Math.round((x-camera.x)*cell)+.5;ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,canvas.height);ctx.stroke();}
    for(let y=start;y<=end;y+=1){const py=Math.round((y-camera.y)*cell)+.5;if(map.id==='normal'||(Math.abs(y)%2===0&&Math.abs(y%5)!==1)){ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(canvas.width,py);ctx.stroke();}}
    if(map.id==='outside'){ctx.fillStyle='#242626';for(let y=Math.max(20,start);y<end;y+=1)for(let x=0;x<map.grid.cols;x+=1)if((x*17+y*11)%29===0){const point=this.layout.worldToScreen(this.grid.gridToWorld(x,y),camera);ctx.fillRect(point.x+cell*.42,point.y+cell*.42,cell*.16,cell*.16);}}
    this.drawBoundary(game,cell,camera);this.drawFood(game,cell,camera);this.drawSnake(game,cell,camera);
  }
  ensureSkin(skin){if(!skin||!skin.renderAssets||this.skinAssets.has(skin.id)||this.loadingSkins.has(skin.id))return;this.loadingSkins.add(skin.id);this.assetLoader.loadSkin(skin).then(assets=>{this.skinAssets.set(skin.id,assets);this.loadingSkins.delete(skin.id);if(this.lastGame?.skinSystem.current.id===skin.id)this.render(this.lastGame);});}
  drawBoundary(game,cell,camera){const map=game.mapSystem.registry.get('normal'),{ctx}=this,{outside}=this.config,top=this.layout.worldToScreen(this.grid.gridToWorld(0,0),camera).y+.5,bottom=this.layout.worldToScreen(this.grid.gridToWorld(0,map.grid.rows),camera).y+.5,start=outside.weakWallStart*cell,end=(outside.weakWallEnd+1)*cell;ctx.strokeStyle='#5e6160';ctx.beginPath();ctx.moveTo(.5,top);ctx.lineTo(this.canvas.width-.5,top);ctx.moveTo(.5,top);ctx.lineTo(.5,bottom);ctx.moveTo(this.canvas.width-.5,top);ctx.lineTo(this.canvas.width-.5,bottom);ctx.moveTo(0,bottom);ctx.lineTo(start,bottom);ctx.moveTo(end,bottom);ctx.lineTo(this.canvas.width,bottom);ctx.stroke();if(game.context.boundaryBroken){ctx.strokeStyle='#8d9190';ctx.beginPath();ctx.moveTo(start,bottom-5);ctx.lineTo(start+5,bottom);ctx.moveTo(end-5,bottom);ctx.lineTo(end,bottom-5);ctx.stroke();}else{ctx.strokeStyle=game.buffSystem.has('break')?'#b7b9b8':'#444646';ctx.beginPath();ctx.moveTo(start,bottom);ctx.lineTo(end,bottom);ctx.stroke();}}
  drawFood(game,cell,camera){const {ctx}=this,food=game.food;if(!food)return;const point=this.layout.worldToScreen(this.grid.gridToWorld(food.x,food.y),camera),sprite=this.resolveSprite(game.skinSystem.current.id,'food');if(food.definition.id==='normal'&&sprite){this.drawSprite(sprite,point.x+cell/2,point.y+cell/2,cell*.82,cell*.82,0,0,true);return;}if(food.definition.id==='break'){ctx.strokeStyle='#d4d6d4';ctx.strokeRect(point.x+cell*.2,point.y+cell*.2,cell*.6,cell*.6);ctx.fillStyle='#d4d6d4';ctx.fillRect(point.x+cell/2-2,point.y+cell/2-2,4,4);}else{ctx.fillStyle='#8d9190';ctx.fillRect(point.x+cell*.14,point.y+cell*.14,cell*.72,cell*.72);}}
  drawSnake(game,cell,camera){const {ctx}=this,segments=game.snake.segments,skin=game.skinSystem.current,profile={...this.config.render.defaultProfile,...(skin.renderProfile??{})};ctx.imageSmoothingEnabled=Boolean(profile.smoothing);for(let index=segments.length-1;index>=0;index-=1){const current=segments[index],point=this.layout.worldToScreen(this.grid.gridToWorld(current.x,current.y),camera);if(point.y<-cell||point.y>this.canvas.height||point.x<-cell||point.x>this.canvas.width)continue;let type,role;if(index===0){type=`head-${directionName(game.snake.direction)}`;role='head';}else if(index===segments.length-1){const previous=segments[index-1];type=`tail-${directionName({x:current.x-previous.x,y:current.y-previous.y})}`;role='tail';}else{type=getSegmentVisualType(segments[index-1],current,segments[index+1]);role=type.startsWith('corner')?'corner':'body';}const sprite=this.resolveSprite(skin.id,type);if(sprite){const scale=profile[`${role}Scale`],offsetX=(profile[`${role}OffsetX`]??0)*cell,offsetY=(profile[`${role}OffsetY`]??0)*cell,drawSize=cell*scale+cell*profile.overlapRatio*2;this.drawSprite(sprite,point.x+cell/2+offsetX,point.y+cell/2+offsetY,drawSize,drawSize,0,0,profile.smoothing);}else{ctx.fillStyle=index===0?'#e8e9e7':'#c8cac8';ctx.fillRect(point.x+cell*.1,point.y+cell*.1,cell*.8,cell*.8);}if(this.config.debug.drawCollisionCells){ctx.strokeStyle='#4f7c7d';ctx.lineWidth=1;ctx.strokeRect(point.x+.5,point.y+.5,cell-1,cell-1);}}}
  resolveSprite(skinId,type){const assets=this.skinAssets.get(skinId),fallback=this.skinAssets.get('default');if(assets?.get(type))return assets.get(type);if(fallback?.get(type))return fallback.get(type);const body=type.includes('vertical')?'body-vertical':'body-horizontal';return assets?.get(body)??fallback?.get(body)??null;}
  drawSprite(image,centerX,centerY,maxWidth,maxHeight,offsetX=0,offsetY=0,smoothing=true){const width=image.naturalWidth||image.width,height=image.naturalHeight||image.height;if(!width||!height)return;this.ctx.imageSmoothingEnabled=Boolean(smoothing);const scale=Math.min(maxWidth/width,maxHeight/height),drawWidth=width*scale,drawHeight=height*scale;this.ctx.drawImage(image,centerX-drawWidth/2+offsetX,centerY-drawHeight/2+offsetY,drawWidth,drawHeight);}
}
