const directionName = vector => vector.x===0&&vector.y===-1?'up':vector.x===0&&vector.y===1?'down':vector.x===-1?'left':'right';
const cornerName = connections => {const names=connections.map(directionName);if(names.includes('up')&&names.includes('left'))return 'corner-ul';if(names.includes('up')&&names.includes('right'))return 'corner-ur';if(names.includes('down')&&names.includes('left'))return 'corner-dl';return 'corner-dr';};

export class RenderSystem {
  constructor(canvas,config,assetLoader){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.config=config;this.assetLoader=assetLoader;this.skinAssets=new Map();this.loadingSkins=new Set();this.lastGame=null;}
  render(game){
    this.lastGame=game;this.ensureSkin(game.skinSystem.current);
    const {ctx,canvas}=this,cell=canvas.width/this.config.gridSize,map=game.mapSystem.current,cameraY=game.cameraSystem.y,visibleY=y=>(y-cameraY)*cell;
    ctx.fillStyle='#0b0c0c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#171919';ctx.lineWidth=1;
    const start=Math.floor(cameraY)-1,end=Math.ceil(cameraY)+this.config.gridSize+1;
    for(let x=0;x<=map.width;x+=1){const px=Math.round(x*cell)+.5;ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,canvas.height);ctx.stroke();}
    for(let y=start;y<=end;y+=1){const py=Math.round(visibleY(y))+.5;if(map.id==='normal'||(Math.abs(y)%2===0&&Math.abs(y%5)!==1)){ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(canvas.width,py);ctx.stroke();}}
    if(map.id==='outside'){ctx.fillStyle='#242626';for(let y=Math.max(20,start);y<end;y+=1)for(let x=0;x<map.width;x+=1)if((x*17+y*11)%29===0)ctx.fillRect(x*cell+cell*.42,visibleY(y)+cell*.42,cell*.16,cell*.16);}
    this.drawBoundary(game,cell,visibleY);this.drawFood(game,cell,visibleY);this.drawSnake(game,cell,visibleY);
  }
  ensureSkin(skin){if(!skin||skin.id==='default'||this.skinAssets.has(skin.id)||this.loadingSkins.has(skin.id))return;this.loadingSkins.add(skin.id);this.assetLoader.loadSkin(skin).then(assets=>{this.skinAssets.set(skin.id,assets);this.loadingSkins.delete(skin.id);if(this.lastGame?.skinSystem.current.id===skin.id)this.render(this.lastGame);});}
  drawBoundary(game,cell,visibleY){const map=game.mapSystem.registry.get('normal');const {ctx}=this,{outside}=this.config,bottom=visibleY(map.height)+.5,top=visibleY(0)+.5,start=outside.weakWallStart*cell,end=(outside.weakWallEnd+1)*cell;ctx.strokeStyle='#5e6160';ctx.beginPath();ctx.moveTo(.5,top);ctx.lineTo(this.canvas.width-.5,top);ctx.moveTo(.5,top);ctx.lineTo(.5,bottom);ctx.moveTo(this.canvas.width-.5,top);ctx.lineTo(this.canvas.width-.5,bottom);ctx.moveTo(0,bottom);ctx.lineTo(start,bottom);ctx.moveTo(end,bottom);ctx.lineTo(this.canvas.width,bottom);ctx.stroke();if(game.context.boundaryBroken){ctx.strokeStyle='#8d9190';ctx.beginPath();ctx.moveTo(start,bottom-5);ctx.lineTo(start+5,bottom);ctx.moveTo(end-5,bottom);ctx.lineTo(end,bottom-5);ctx.stroke();}else{ctx.strokeStyle=game.buffSystem.has('break')?'#b7b9b8':'#444646';ctx.beginPath();ctx.moveTo(start,bottom);ctx.lineTo(end,bottom);ctx.stroke();}}
  drawFood(game,cell,visibleY){const {ctx}=this,food=game.world.entities.get('food');if(!food)return;const x=food.x*cell,y=visibleY(food.y),sprite=this.skinAssets.get(game.skinSystem.current.id)?.get('food');if(food.definition.id==='normal'&&sprite){this.drawSprite(sprite,x+cell/2,y+cell/2,cell*.86,cell*.86);return;}if(food.definition.id==='break'){ctx.strokeStyle='#d4d6d4';ctx.strokeRect(x+6,y+6,cell-12,cell-12);ctx.fillStyle='#d4d6d4';ctx.fillRect(x+cell/2-2,y+cell/2-2,4,4);}else{ctx.fillStyle='#8d9190';ctx.fillRect(x+4,y+4,cell-8,cell-8);}}
  drawSnake(game,cell,visibleY){const {ctx}=this,segments=game.snake.segments,assets=this.skinAssets.get(game.skinSystem.current.id);for(let index=segments.length-1;index>=0;index-=1){const segment=segments[index],x=segment.x*cell,y=visibleY(segment.y);if(y<-cell||y>this.canvas.height)continue;let assetName=null;if(assets){if(index===0)assetName=`head-${directionName(game.snake.direction)}`;else if(index===segments.length-1){const previous=segments[index-1];assetName=`tail-${directionName({x:segment.x-previous.x,y:segment.y-previous.y})}`;}else{const previous=segments[index-1],next=segments[index+1],connections=[{x:previous.x-segment.x,y:previous.y-segment.y},{x:next.x-segment.x,y:next.y-segment.y}],horizontal=connections.every(connection=>connection.y===0),vertical=connections.every(connection=>connection.x===0);assetName=horizontal?'body-horizontal':vertical?'body-vertical':cornerName(connections);}}const sprite=assetName?assets?.get(assetName):null;if(sprite){const horizontal=assetName==='body-horizontal'||assetName.endsWith('-left')||assetName.endsWith('-right'),vertical=assetName==='body-vertical'||assetName.endsWith('-up')||assetName.endsWith('-down');this.drawSprite(sprite,x+cell/2,y+cell/2,horizontal?cell*1.8:cell*1.18,vertical?cell*1.8:cell*1.18);}else{ctx.fillStyle=index===0?'#e8e9e7':'#c8cac8';ctx.fillRect(x+2,y+2,cell-4,cell-4);}}}
  drawSprite(image,centerX,centerY,maxWidth,maxHeight){const width=image.naturalWidth||image.width,height=image.naturalHeight||image.height;if(!width||!height)return;const scale=Math.min(maxWidth/width,maxHeight/height),drawWidth=width*scale,drawHeight=height*scale;this.ctx.drawImage(image,centerX-drawWidth/2,centerY-drawHeight/2,drawWidth,drawHeight);}
}
