import { GameState, RunMode } from '../core/GameState.js';

const statusLabels={READY:'Ready',RUNNING:'Running',PAUSED:'Paused',GAME_OVER:'Game over',MODAL:'Auth',TRANSITION:'Unknown'};
const timeText=ms=>{const seconds=Math.floor(ms/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;};

export class UISystem {
  constructor({ game, skinSystem, profileService, redeemService, saveService, eventBus, foodRegistry }) {
    this.game=game;this.skinSystem=skinSystem;this.profile=profileService;this.redeemService=redeemService;this.save=saveService;this.eventBus=eventBus;this.foodRegistry=foodRegistry;this.konami=[];this.returnState=GameState.PAUSED;
    this.el=Object.fromEntries(['score','best-score','pause-button','restart-button','mode-status','world-status','state-status','buff-status','start-screen','start-button','start-skin-name','start-skin-preview','pause-overlay','message','message-title','message-text','game-over-stats','final-score','final-best','final-length','final-time','outside-note','verification-modal','verification-form','code-input','dialog-error','dialog-close','redeem-modal','redeem-form','redeem-input','redeem-error','redeem-close','redeem-button'].map(id=>[id,document.getElementById(id)]));
    this.diffButtons=[...document.querySelectorAll('[data-difficulty]')];this.skinButtons=[...document.querySelectorAll('[data-skin]')];this.dirButtons=[...document.querySelectorAll('[data-direction]')];
  }
  bind(){this.el['pause-button'].addEventListener('click',()=>this.game.togglePause());this.el['restart-button'].addEventListener('click',()=>this.game.reset());this.el['start-button'].addEventListener('click',()=>this.start());document.addEventListener('keydown',event=>{if(event.key==='Enter'&&this.start()){event.preventDefault();}});this.diffButtons.forEach(button=>button.addEventListener('click',()=>{if(this.game.chooseDifficulty(button.dataset.difficulty))this.save.update(save=>{save.settings.difficulty=button.dataset.difficulty;});this.update();}));this.skinButtons.forEach(button=>button.addEventListener('click',()=>{this.skinSystem.equip(button.dataset.skin);this.game.reset();}));this.dirButtons.forEach(button=>button.addEventListener('click',()=>this.direction(button.dataset.direction)));this.el['redeem-button'].addEventListener('click',()=>this.openRedeem());this.el['dialog-close'].addEventListener('click',()=>this.closeCheat());this.el['redeem-close'].addEventListener('click',()=>this.closeRedeem());this.el['verification-form'].addEventListener('submit',event=>this.verifyCheat(event));this.el['redeem-form'].addEventListener('submit',event=>this.redeem(event));['game:start','game:restart','game:pause','game:resume','game:over','score:change','skin:equip','skin:unlock','buff:add','buff:remove','map:enter','mode:change'].forEach(name=>this.eventBus.on(name,()=>this.update()));this.eventBus.on('secret:discover',({secretId})=>this.profile.discover(secretId));this.eventBus.on('game:over',()=>this.recordRun());this.update();}
  start(){if(this.game.state!==GameState.READY)return false;this.game.start();return true;}
  direction(name){if(this.game.state===GameState.READY)return false;return this.game.queueDirection(this.game.config.directions[name]);}
  toggleSpace(){if(this.game.state===GameState.MODAL)return true;if(this.game.state===GameState.READY)return this.start();this.game.togglePause();return true;}
  restart(){if([GameState.PAUSED,GameState.GAME_OVER].includes(this.game.state)){this.game.reset();return true;}return false;}
  pausedKey(key){if(this.game.state!==GameState.PAUSED||this.game.context.runMode!==RunMode.NORMAL)return false;const input=key.startsWith('Arrow')?key:(['a','b'].includes(key.toLowerCase())?key.toLowerCase():null);if(!input){this.konami=[];return false;}this.konami.push(input);if(this.konami.length>10)this.konami.shift();const sequence=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];if(sequence.every((entry,index)=>this.konami[index]===entry)){this.konami=[];this.openCheat();}return true;}
  openCheat(){this.returnState=this.game.state;this.game.openModal('cheat');this.el['verification-form'].reset();this.el['dialog-error'].textContent='';this.el['verification-modal'].hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>this.el['code-input'].focus());this.update();}
  closeCheat(){this.el['verification-modal'].hidden=true;document.body.classList.remove('modal-open');this.game.closeModal(GameState.PAUSED);this.update();}
  verifyCheat(event){event.preventDefault();if(this.el['code-input'].value.trim().toLowerCase()!=='mario'){this.el['dialog-error'].textContent='口令不正确，请重试。';this.el['code-input'].select();return;}this.game.setRunMode(RunMode.CHEAT);this.game.buffSystem.remove('break');if(this.game.food?.definition.id==='break')this.game.food.definition=this.foodRegistry.get('normal');this.closeCheat();}
  openRedeem(){if(![GameState.READY,GameState.GAME_OVER].includes(this.game.state))return;this.returnState=this.game.state;this.game.openModal('redeem');this.el['redeem-form'].reset();this.el['redeem-error'].textContent='';this.el['redeem-modal'].hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>this.el['redeem-input'].focus());this.update();}
  closeRedeem(){this.el['redeem-modal'].hidden=true;document.body.classList.remove('modal-open');this.game.closeModal(this.returnState);this.update();}
  redeem(event){event.preventDefault();const result=this.redeemService.redeem(this.el['redeem-input'].value);if(!result.success){this.el['redeem-error'].textContent=result.message;this.el['redeem-input'].select();return;}let skin=null;if(result.rewardType==='skin'){this.skinSystem.unlock(result.rewardId);this.skinSystem.equip(result.rewardId);skin=this.skinSystem.current;}this.closeRedeem();this.game.reset();this.el['message-title'].textContent=result.message;this.el['message-text'].textContent=skin?`已选择 ${skin.displayName}。`:'';this.el.message.hidden=false;this.update();}
  escape(){if(!this.el['verification-modal'].hidden){this.closeCheat();return true;}if(!this.el['redeem-modal'].hidden){this.closeRedeem();return true;}return false;}
  recordRun(){const game=this.game;const category=game.context.runMode===RunMode.CHEAT?'cheatBestScore':game.context.runMode===RunMode.ASSISTED?'assistedBestScore':'normalBestScore';this.save.update(save=>{save.stats[category]=Math.max(save.stats[category],game.score.value);save.stats.totalRuns+=1;save.stats.totalScore+=game.score.value;});this.update();}
  update(){const game=this.game,state=game.state,skin=this.skinSystem.current,mode=game.context.runMode;const currentBest=this.save.save.stats[mode===RunMode.CHEAT?'cheatBestScore':mode===RunMode.ASSISTED?'assistedBestScore':'normalBestScore'];this.el.score.textContent=game.score.value;this.el['best-score'].textContent=currentBest;this.el['pause-button'].disabled=![GameState.RUNNING,GameState.PAUSED].includes(state);this.el['pause-button'].textContent=state===GameState.PAUSED?'继续':'暂停';this.el['mode-status'].textContent=mode===RunMode.CHEAT?'Cheat':skin.displayName;this.el['mode-status'].dataset.mode=mode===RunMode.CHEAT?'cheat':skin.id;this.el['world-status'].textContent=game.mapSystem.current.id==='outside'&&game.context.mapStatusKnown?'Outside':'Normal';this.el['state-status'].textContent=statusLabels[state];this.el['buff-status'].textContent=game.buffSystem.has('break')?'Unstable':'';const setup=[GameState.READY,GameState.GAME_OVER].includes(state);this.diffButtons.forEach(button=>{button.disabled=!setup;button.setAttribute('aria-pressed',String(button.dataset.difficulty===game.context.difficulty));});this.skinButtons.forEach(button=>{const owned=this.profile.owns(button.dataset.skin);button.hidden=!owned;button.disabled=!setup;button.setAttribute('aria-pressed',String(button.dataset.skin===skin.id));});this.el['redeem-button'].disabled=!setup;this.el['start-button'].disabled=state!==GameState.READY;this.el['start-screen'].hidden=state!==GameState.READY;this.el['pause-overlay'].hidden=state!==GameState.PAUSED;this.el['start-skin-name'].textContent=skin.displayName;this.el['start-skin-preview'].hidden=!skin.previewPath;if(skin.previewPath)this.el['start-skin-preview'].src=skin.previewPath;if(state===GameState.GAME_OVER){this.el.message.hidden=false;this.el['message-title'].textContent='本局结束';this.el['message-text'].textContent=mode===RunMode.CHEAT?'CHEAT':'按 R 或重新开始。';this.el['final-score'].textContent=game.score.value;this.el['final-best'].textContent=currentBest;this.el['final-length'].textContent=game.snake.length;this.el['final-time'].textContent=timeText(game.duration);this.el['outside-note'].hidden=!this.profile.profile.discoveries.includes('outside-discovered');this.el['game-over-stats'].hidden=false;}else{this.el.message.hidden=true;this.el['game-over-stats'].hidden=true;}document.body.dataset.theme=game.mapSystem.current.id==='outside'?'outside':skin.uiThemeId||'default';}
}
