import { GameState, RunMode, isPlaying } from './GameState.js';
import { Snake } from './Snake.js';
import { Score } from './Score.js';

export class Game {
  constructor({ config, eventBus, mapSystem, cameraSystem, buffSystem, mechanicSystem, skinSystem, renderSystem }) {
    this.config=config;this.eventBus=eventBus;this.mapSystem=mapSystem;this.cameraSystem=cameraSystem;this.buffSystem=buffSystem;this.mechanicSystem=mechanicSystem;this.skinSystem=skinSystem;this.renderSystem=renderSystem;
    this.snake=new Snake(config.initialSnake,config.directions.right);this.score=new Score();this.world={entities:new Map()};this.state=GameState.READY;this.context={worldId:'normal',mapId:'normal',runMode:RunMode.NORMAL,activeModal:null,difficulty:'normal',nextFoodId:null,boundaryBroken:false,activeMapEnteredAt:0,mapStatusKnown:false};this.elapsed=0;this.clockAt=null;this.timer=null;this.transitionTimers=[];
  }
  get isPlaying(){return isPlaying(this.state);}
  get food(){return this.world.entities.get('food');}
  setState(state){this.state=state;}
  setRunMode(mode){this.context.runMode=mode;this.eventBus.emit('mode:change',{mode});}
  reset(){this.stopAll();this.freezeClock();this.elapsed=0;this.clockAt=null;this.score.reset();this.snake.reset(this.config.initialSnake,this.config.directions.right);this.buffSystem.reset();this.mapSystem.enter('normal');this.cameraSystem.reset();this.context={...this.context,worldId:'normal',mapId:'normal',runMode:RunMode.NORMAL,activeModal:null,nextFoodId:null,boundaryBroken:false,activeMapEnteredAt:0,mapStatusKnown:false};this.mechanicSystem.configure([...this.skinSystem.current.mechanics,...this.mapSystem.current.mechanics],{game:this});this.spawnFood();this.setState(GameState.READY);this.eventBus.emit('game:restart',{game:this});this.render();}
  start(){if(this.state===GameState.READY){this.resumeClock();this.setState(GameState.RUNNING);this.eventBus.emit('game:start',{game:this});this.schedule();}else if(this.state===GameState.PAUSED){this.resumeClock();this.setState(GameState.RUNNING);this.eventBus.emit('game:resume',{game:this});this.schedule();}}
  pause(){if(!this.isPlaying)return;this.stopTick();this.freezeClock();this.setState(GameState.PAUSED);this.eventBus.emit('game:pause',{game:this});}
  togglePause(){if(this.isPlaying)this.pause();else if(this.state===GameState.PAUSED)this.start();}
  openModal(id){if(![GameState.READY,GameState.PAUSED,GameState.GAME_OVER].includes(this.state))return false;this.context.activeModal=id;this.setState(GameState.MODAL);this.eventBus.emit('ui:modal-open',{id,game:this});return true;}
  closeModal(next=GameState.PAUSED){if(this.state!==GameState.MODAL)return;const id=this.context.activeModal;this.context.activeModal=null;this.setState(next);this.eventBus.emit('ui:modal-close',{id,game:this});}
  queueDirection(direction){if(![GameState.READY,GameState.RUNNING].includes(this.state))return false;const changed=this.snake.queueDirection(direction);if(changed&&this.state===GameState.READY)this.start();return changed;}
  chooseDifficulty(id){if(![GameState.READY,GameState.GAME_OVER].includes(this.state)||!this.config.difficulty[id])return false;this.context.difficulty=id;return true;}
  schedule(){this.stopTick();this.timer=window.setTimeout(()=>this.tick(),this.config.difficulty[this.context.difficulty].speed);}
  stopTick(){window.clearTimeout(this.timer);this.timer=null;}
  stopAll(){this.stopTick();this.transitionTimers.forEach(timer=>window.clearTimeout(timer));this.transitionTimers=[];}
  resumeClock(){if(this.clockAt===null)this.clockAt=performance.now();}
  freezeClock(){if(this.clockAt!==null){this.elapsed+=performance.now()-this.clockAt;this.clockAt=null;}}
  get duration(){return this.elapsed+(this.clockAt===null?0:performance.now()-this.clockAt);}
  spawnFood(){const food=this.mapSystem.spawnFood(this.snake,this.context.nextFoodId);this.context.nextFoodId=null;if(food)this.world.entities.set('food',food);else this.world.entities.delete('food');return food;}
  tick(){if(!this.isPlaying)return;let head=this.snake.nextHead();if(this.context.runMode===RunMode.CHEAT||this.mapSystem.current.boundaryMode==='open-x')head=this.mapSystem.wrap(head,this.context.runMode===RunMode.CHEAT);const collision=this.mapSystem.collisionAt(head);const self=this.snake.collidesWithBody(head,Boolean(this.food&&head.x===this.food.x&&head.y===this.food.y));const mechanicResponses=this.mechanicSystem.run('onCollision',{game:this,head,collision,self});const transition=mechanicResponses.find(result=>result?.transition)?.transition;const protectedCollision=mechanicResponses.some(result=>result?.preventDeath);this.eventBus.emit('snake:collision',{game:this,head,collision,self,protectedCollision});if(transition){this.beginTransition(head,transition);return;}if(this.context.runMode!==RunMode.CHEAT&&(collision.wall||self)&&!protectedCollision){this.gameOver();return;}const food=this.food;const eats=food&&food.x===head.x&&head.y===food.y;this.snake.move(head,Boolean(eats));this.eventBus.emit('snake:move',{game:this,head});if(eats)this.consumeFood(food);this.cameraSystem.update(this.snake.head);if(!this.context.mapStatusKnown&&this.mapSystem.current.statusDelay&&performance.now()-this.context.activeMapEnteredAt>=this.mapSystem.current.statusDelay)this.context.mapStatusKnown=true;this.render();this.schedule();}
  consumeFood(food){this.world.entities.delete('food');const multiplier=this.context.runMode===RunMode.CHEAT?2:1;const amount=food.definition.score*multiplier;this.score.add(amount);if(food.definition.buffId)this.buffSystem.apply(food.definition.buffId);this.eventBus.emit('snake:eat',{game:this,food});this.eventBus.emit('snake:grow',{game:this,amount:food.definition.growth});this.eventBus.emit('score:change',{game:this,amount,score:this.score.value});this.mechanicSystem.run('onScoreChanged',{game:this,score:this.score.value});if(!this.spawnFood())this.gameOver();}
  beginTransition(head,transition){this.stopTick();this.freezeClock();this.snake.move(head,false);this.context.boundaryBroken=true;this.buffSystem.consume('break');this.setState(GameState.TRANSITION);this.eventBus.emit('world:boundary-break',{game:this,transition});this.render();const apply=()=>{this.snake.shrink(transition.trimAmount,transition.minLength);this.mapSystem.enter(transition.mapId);this.context.worldId=transition.mapId;this.context.mapId=transition.mapId;this.context.activeMapEnteredAt=performance.now();this.context.mapStatusKnown=false;this.cameraSystem.update(this.snake.head);this.eventBus.emit('map:enter',{map:this.mapSystem.current,game:this});if(transition.secretId)this.eventBus.emit('secret:discover',{secretId:transition.secretId,game:this});this.resumeClock();this.setState(GameState.RUNNING);this.render();this.schedule();};this.transitionTimers.push(window.setTimeout(apply,transition.delay??0));}
  gameOver(){this.stopAll();this.freezeClock();this.setState(GameState.GAME_OVER);this.eventBus.emit('snake:death',{game:this});this.eventBus.emit('game:over',{game:this});this.render();}
  render(){this.renderSystem.render(this);}
}
